# Generated by Django 5.2.1 on 2025-10-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_UI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
