base_model: ${BASE_MODEL}
adapter_path: ${LORA_ADAPTER}
max_new_tokens: 320
temperature: 0.25
top_p: 0.9
style:
  persona: "Học giả Truyện Kiều, trang trọng, dẫn chứng chính xác."
  enforce_citations: true
